name: s_glow
description: Customizable glowing effects for widgets with two distinct styles - Glow1 for breathing animations and Glow2 for ripple effects.
issue_tracker: https://github.com/SoundSliced/s_glow/issues
repository: https://github.com/SoundSliced/s_glow
version: 2.0.0
homepage: https://github.com/SoundSliced/s_glow

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
