name: s_glow
description: A Flutter package providing customizable glowing effects for widgets with two distinct styles - Glow1 for breathing animations and Glow2 for ripple effects.
version: 1.0.0
homepage: https://github.com/christophechanteur/s_glow

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  soundsliced_tween_animation_builder: ^1.2.0
  states_rebuilder_extended: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
